name: CI Pipeline

on:
  pull_request:
    branches: [ main, test-branch ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          pip install ruff
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
      POSTGRES_DB_UNIVERSITY: ${{ secrets.POSTGRES_DB_UNIVERSITY }}
      AUTH_SERVICE_INTERNAL_URL: ${{ secrets.AUTH_SERVICE_INTERNAL_URL }}
      AUTH_SERVICE_API_URL: ${{ secrets.AUTH_SERVICE_API_URL }}
      UNIVERSITY_SERVICE_INTERNAL_URL: ${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
      UNIVERSITY_SERVICE_API_URL: ${{ secrets.UNIVERSITY_SERVICE_API_URL }}
      PYTHONPATH: .

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run tests
        run: |
          pip install -r requirements.txt
          docker compose up -d --build
          echo "⏳ Waiting for services to be ready..."
          sleep 15
          echo "🚀 Running pytest..."
          pytest --alluredir=allure-results --maxfail=9999 --disable-warnings --tb=short || true
          echo "✅ Tests completed"
          ls -la allure-results || echo "⚠️ No Allure results found!"

      - name: Upload allure-results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  report:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Download allure-results artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          ALLURE_VERSION=2.27.0
          wget -q https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
          unzip -q allure-${ALLURE_VERSION}.zip -d $HOME/allure
          echo "$HOME/allure/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH
          export PATH="$HOME/allure/allure-${ALLURE_VERSION}/bin:$PATH"
          allure --version

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            allure generate allure-results --clean -o allure-report
          else
            echo "⚠️ No allure-results found. Skipping report generation."
            echo "<html><body><h1>No Allure Results Found</h1></body></html>" > allure-report/index.html
          fi
          ls -la allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true