name: GitHub Actions Test

on:
  push:
    branches: [ main, test-branch ]
  pull_request:
    branches: [ main, test-branch ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB_AUTH: auth_db
      POSTGRES_DB_UNIVERSITY: university_db
      AUTH_SERVICE_INTERNAL_URL: http://auth-service:8000
      AUTH_SERVICE_API_URL: http://localhost:8000
      UNIVERSITY_SERVICE_INTERNAL_URL: http://university-service:8001
      UNIVERSITY_SERVICE_API_URL: http://localhost:8001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest allure-pytest requests faker docker

      - name: Run Ruff linter
        run: ruff check . || echo "Ruff found style issues"

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for auth-service and university-service"
          for i in {1..30}; do
            if curl -s http://localhost:8000/health > /dev/null && curl -s http://localhost:8001/health > /dev/null; then
              echo "Services are ready"
              exit 0
            fi
            sleep 5
          done
          echo "Services not responding in time" && exit 1

      - name: Run API tests
        env:
          PYTHONPATH: .
        run: pytest tests/ --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report || echo "Allure report failed"

      - name: Deploy Allure report to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report